### PR TITLE
Leave cache of frameworks that are successfully built

### LINKED ISSUE #153: Saving caches and versions file even if some frameworks fail to build
https://github.com/giginet/Scipio/blob/4c2cc399ab771993b2b94db6490fe9c926ee68aa/Sources/ScipioKit/Producer/FrameworkProducer.swift#L124-L141

Even if some frameworks fail to build, we can still save caches and version files for successfully-built frameworks. That would reduce build time for next attempts.

### PR DESCRIPTION
**Pull request by S-Shimotori**
Closes #153 

This PR will fix the issue reported by #153.

# Changes

## FrameworkProducer

`processAllTargets(buildProducts:)` will cache XCFrameworks that are successfully built.
Scipio users won't have to rebuild all frameworks even if Scipio fails to build some frameworks.

## PartialCacheTests

`PartialCacheTests` checks that `processAllTargets(buildProducts:)` works well.

Tests/ScipioKitTests/Resources/Fixtures/PartialCacheTestPackage provides two libraries, `Base` and `Bad.`
`Bad` depends on `Base` and cannot be compiled.

### CODE REVIEW

File: Tests/ScipioKitTests/PartialCacheTests.swift [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+    .appendingPathComponent("Resources")
+    .appendingPathComponent("Fixtures")
+
+struct PartialCacheTests {
+    private let fileManager: FileManager = .default
+    private let tempDir: URL
+    private let frameworkOutputDir: URL
+
+    init() throws {
+        LoggingSystem.bootstrap { _ in SwiftLogNoOpLogHandler() }
```
Comment (giginet) [inline Tests/ScipioKitTests/PartialCacheTests.swift:17]: I tried to run the tests for this PR, it seems that we should remove this line to pass the tests.

Maybe this should be called once during the entire test execution.

File: Tests/ScipioKitTests/PartialCacheTests.swift [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+import Testing
+@testable import ScipioKit
+import Logging
+
+private let fixturePath = URL(fileURLWithPath: #filePath)
+    .deletingLastPathComponent()
+    .appendingPathComponent("Resources")
+    .appendingPathComponent("Fixtures")
+
+struct PartialCacheTests {
```
Comment (giginet) [inline Tests/ScipioKitTests/PartialCacheTests.swift:11]: @S-Shimotori I found the cause of CI failing.

Please add `@Suite(.serialized)` on your test.
And cherry-pick this commit. https://github.com/giginet/Scipio/pull/185/commits/d9415621bb2c253c65310f142d501015a49fb08f

File: Tests/ScipioKitTests/PartialCacheTests.swift (hunk 1 above)
Comment (S-Shimotori) [reply Tests/ScipioKitTests/PartialCacheTests.swift]: Removed https://github.com/giginet/Scipio/pull/184/commits/34f7efcc8c98190afe8d904cdaac59dfcb234177

File: Tests/ScipioKitTests/PartialCacheTests.swift (hunk 2 above)
Comment (S-Shimotori) [reply Tests/ScipioKitTests/PartialCacheTests.swift:10]: Thank you! I cherry-picked the commit.

File: Sources/ScipioKit/Producer/FrameworkProducer.swift [hunk 3]
```diff
@@ -304,6 +302,26 @@ struct FrameworkProducer {
         }
     }
 
+    private func buildTargets(
+        _ targets: OrderedSet<CacheSystem.CacheTarget>
+    ) async -> (OrderedSet<CacheSystem.CacheTarget>, (any Error)?) {
```
Comment (giginet) [inline Sources/ScipioKit/Producer/FrameworkProducer.swift:307]: Could you make a result model instead of returning tuple?

```swift
enum TargetBuildResult {
    case interrupted(OrderedSet<CacheSystem.CacheTarget>, any Error)
    case completed(OrderedSet<CacheSystem.CacheTarget>)
}
```

File: Tests/ScipioKitTests/PartialCacheTests.swift (hunk 2 above)
Comment (giginet) [reply Tests/ScipioKitTests/PartialCacheTests.swift:10]:
```suggestion
@Suite(.serialized)
struct PartialCacheTests {
```

Please add the same annotation here.

**Review by giginet — APPROVED** [review]

File: Sources/ScipioKit/Producer/FrameworkProducer.swift [hunk 4]
```diff
@@ -124,22 +124,26 @@ struct FrameworkProducer {
...
             // Versionfiles should be generate for all targets
-            for target in allTargets {
+            for target in builtTargets {
                 await generateVersionFile(for: target, using: cacheSystem)
             }
         }
+
+        if case .interrupted(builtTargets: _, error: let error) = targetBuildResult {
+            throw error
+        }
```
Comment (ikesyo) [inline Sources/ScipioKit/Producer/FrameworkProducer.swift:146]:
```suggestion
        if case .interrupted(_, error) = targetBuildResult {
            throw error
        }
```

This could be simplified (not mandatory).

File: Sources/ScipioKit/Producer/FrameworkProducer.swift [hunk 5]
```diff
@@ -124,22 +124,26 @@ struct FrameworkProducer {
...
-                target,
-                outputDir: outputDir,
-                buildOptionsMatrix: buildOptionsMatrix
-            )
-        }
+        let targetBuildResult = await buildTargets(targetsToBuild)
+
+        let builtTargets: OrderedSet<CacheSystem.CacheTarget> = switch targetBuildResult {
+            case .completed(builtTargets: let builtTargets),
+                 .interrupted(builtTargets: let builtTargets, error: _):
```
Comment (ikesyo) [inline Sources/ScipioKit/Producer/FrameworkProducer.swift:131]:
```suggestion
            case .completed(let builtTargets),
                 .interrupted(let builtTargets, _):
```

File: Tests/ScipioKitTests/PartialCacheTests.swift (hunk 2 above)
Comment (S-Shimotori) [reply Tests/ScipioKitTests/PartialCacheTests.swift:11]: I forgot that. Sorry https://github.com/giginet/Scipio/pull/184/commits/70cecbed738ce45af71ed24f82bdc563087ad903

**Review by giginet — APPROVED** [review]

**Comment by giginet** [comment]
build was broken 😢

File: Sources/ScipioKit/Producer/FrameworkProducer.swift [hunk 6]
```diff
@@ -124,22 +124,26 @@ struct FrameworkProducer {
...
 
         if shouldGenerateVersionFile {
             // Versionfiles should be generate for all targets
-            for target in allTargets {
+            for target in builtTargets {
                 await generateVersionFile(for: target, using: cacheSystem)
             }
         }
+
+        if case .interrupted(_, error) = targetBuildResult {
```
Comment (ikesyo) [inline Sources/ScipioKit/Producer/FrameworkProducer.swift:144]:
```suggestion
        if case .interrupted(_, let error) = targetBuildResult {
```

I'm sorry for my previous missuggestion. 🙇

**Comment by S-Shimotori** [comment]
I'm so sorry..

**Review by giginet — APPROVED** [review]

**Review by ikesyo — APPROVED** [review]
